import type { SiteContent } from "@/content/schema";

export const siteContentTh: SiteContent = {
  locale: "th",
  htmlLang: "th",
  siteName: "Tan & Top Wedding",
  coupleFriendlyName: "Tan & Top",
  coupleFormalName: "Narueporn & Theerut",
  weddingDate: "วันอาทิตย์ที่ 29 พฤศจิกายน 2569",
  logoHref: "/",
  linePageHref: "/line",
  navDesktop: [
    { href: "/schedule", label: "กำหนดการ" },
    { href: "/venue", label: "สถานที่" },
    { href: "/gallery", label: "แกลเลอรี" },
    { href: "/faq", label: "คำถามที่พบบ่อย" },
  ],
  navMobile: [
    { href: "/schedule", label: "กำหนดการ" },
    { href: "/venue", label: "สถานที่" },
    { href: "/gallery", label: "แกลเลอรี" },
    { href: "/faq", label: "คำถามที่พบบ่อย" },
  ],
  bottomNav: [
    { href: "/", label: "หน้าหลัก", icon: "home" },
    { href: "/schedule", label: "กำหนดการ", icon: "calendar" },
    { href: "/venue", label: "สถานที่", icon: "mapPin" },
    { href: "/gallery", label: "แกลเลอรี", icon: "images" },
    { href: "/faq", label: "คำถาม", icon: "circleHelp" },
  ],
  languageSwitchLabel: "EN",
  mobileMenuOpenLabel: "เปิดเมนู",
  mobileMenuCloseLabel: "ปิดเมนู",
  homeShell: {
    invitationCardEyebrow: "วันสำคัญของเรา",
    formalNames: "Narueporn & Theerut",
    dateLabel: "วันอาทิตย์ที่ 29 พฤศจิกายน 2569",
    locationLabel: "Conrad Bangkok",
    invitationProgrammeSummary: "พิธีช่วงเช้าและงานเลี้ยงฉลองมงคลสมรส",
    invitationCtaLabel: "ดูรายละเอียด",
    invitationCtaHref: "/#quick-actions",
    supportLineLabel: "ไปยังหน้า LINE Official Account",
    quickActionCards: [
      {
        href: "/schedule",
        title: "กำหนดการ",
        subtitle: "ดูตารางเวลาของวันงาน",
        icon: "calendar",
      },
      {
        href: "/venue",
        title: "สถานที่",
        subtitle: "แผนที่และข้อมูลการเดินทาง",
        icon: "mapPin",
      },
      {
        href: "/gallery",
        title: "แกลเลอรี",
        subtitle: "ภาพความทรงจำของเรา",
        icon: "images",
      },
      {
        href: "/faq",
        title: "คำถามที่พบบ่อย",
        subtitle: "ข้อมูลสำคัญสำหรับแขก",
        icon: "circleHelp",
      },
    ],
    welcomeTitle: "จากใจของเรา",
    welcomeMessage:
      "ขอบคุณที่มาร่วมเป็นส่วนหนึ่งของวันสำคัญของเรา เราหวังว่าเว็บไซต์นี้จะช่วยให้ทุกท่านเตรียมตัวและเดินทางมาร่วมงานได้อย่างสะดวก",
  },
  footer: {
    thankYou: "ขอบคุณที่มาร่วมเป็นส่วนหนึ่งของวันสำคัญของเรา",
    lineLabel: "ช่องทางอัปเดตอย่างเป็นทางการ",
    lineLinkText: "LINE OA",
    venueLabel: "Conrad Bangkok",
    footerLinks: [
      { href: "/schedule", label: "กำหนดการ" },
      { href: "/venue", label: "สถานที่" },
      { href: "/gallery", label: "แกลเลอรี" },
      { href: "/faq", label: "คำถามที่พบบ่อย" },
    ],
  },
};
