import type { SiteContent } from "@/content/schema";

export const siteContentTh: SiteContent = {
  locale: "th",
  htmlLang: "th",
  siteName: "Tan & Top Wedding",
  coupleFriendlyName: "Tan & Top",
  coupleFormalName: "Narueporn & Theerut",
  weddingDate: "วันอาทิตย์ที่ 29 พฤศจิกายน 2569",
  logoHref: "/",
  linePageHref: "/line",
  navDesktop: [
    { href: "/schedule", label: "กำหนดการ" },
    { href: "/venue", label: "สถานที่" },
    { href: "/gallery", label: "แกลเลอรี" },
    { href: "/faq", label: "คำถามที่พบบ่อย" },
  ],
  navMobile: [
    { href: "/schedule", label: "กำหนดการ" },
    { href: "/venue", label: "สถานที่" },
    { href: "/gallery", label: "แกลเลอรี" },
    { href: "/faq", label: "คำถามที่พบบ่อย" },
  ],
  languageSwitchLabel: "EN",
  mobileMenuOpenLabel: "เปิดเมนู",
  mobileMenuCloseLabel: "ปิดเมนู",
  homeShell: {
    title: "Wedding 2026",
    formalNames: "Narueporn & Theerut",
    dateLabel: "วันอาทิตย์ที่ 29 พฤศจิกายน 2569",
    locationLabel: "Conrad Bangkok",
    intro:
      "เราตั้งใจทำเว็บไซต์นี้ขึ้นมาเพื่อรวบรวมรายละเอียดสำคัญของงานแต่งงานไว้ในที่เดียว ทั้งกำหนดการ สถานที่ แผนที่ และแกลเลอรี เพื่อให้แขกทุกท่านสามารถเปิดดูข้อมูลได้สะดวกก่อนถึงวันงาน",
    primaryCtaLabel: "ดูกำหนดการ",
    primaryCtaHref: "/schedule",
    secondaryCtaLabel: "ดูแผนที่",
    secondaryCtaHref: "/venue",
    supportLineLabel: "ไปยังหน้า LINE Official Account",
    quickLinks: [],
    quickLinksLabel: "ภาพรวมวันสำคัญ",
    glanceTitle: "ภาพรวมวันสำคัญ",
    glanceCards: [
      { label: "วันที่", value: "วันอาทิตย์ที่ 29 พฤศจิกายน 2569" },
      { label: "สถานที่", value: "Conrad Bangkok" },
      { label: "ช่วงเวลา", value: "พิธีช่วงเช้าและงานเลี้ยงฉลองมงคลสมรส" },
    ],
    welcomeTitle: "จากใจของเรา",
    welcomeMessage:
      "ขอบคุณที่มาร่วมเป็นส่วนหนึ่งของวันสำคัญของเรา เราหวังว่าเว็บไซต์นี้จะช่วยให้ทุกท่านเตรียมตัวและเดินทางมาร่วมงานได้อย่างสะดวก",
    heroImageAlt: "[ภาพหลัก placeholder]",
    heroImageCaption: "[ภาพหลัก placeholder]",
    heroImageCategory: "hero",
  },
  footer: {
    thankYou: "ขอบคุณที่มาร่วมเป็นส่วนหนึ่งของวันสำคัญของเรา",
    lineLabel: "ช่องทางอัปเดตอย่างเป็นทางการ",
    lineLinkText: "LINE OA",
    venueLabel: "Conrad Bangkok",
    footerLinks: [
      { href: "/schedule", label: "กำหนดการ" },
      { href: "/venue", label: "สถานที่" },
      { href: "/gallery", label: "แกลเลอรี" },
      { href: "/faq", label: "คำถามที่พบบ่อย" },
    ],
  },
};
