import type { SiteContent } from "@/content/schema";

export const siteContentEn: SiteContent = {
  locale: "en",
  htmlLang: "en",
  siteName: "Tan & Top Wedding",
  coupleFriendlyName: "Tan & Top",
  coupleFormalName: "Narueporn & Theerut",
  weddingDate: "Sunday, 29 November 2026",
  logoHref: "/en",
  linePageHref: "/en/line",
  navDesktop: [
    { href: "/en/schedule", label: "Schedule" },
    { href: "/en/venue", label: "Venue" },
    { href: "/en/gallery", label: "Gallery" },
    { href: "/en/faq", label: "FAQ" },
  ],
  navMobile: [
    { href: "/en/schedule", label: "Schedule" },
    { href: "/en/venue", label: "Venue" },
    { href: "/en/gallery", label: "Gallery" },
    { href: "/en/faq", label: "FAQ" },
  ],
  bottomNav: [
    { href: "/en", label: "Home", icon: "home" },
    { href: "/en/schedule", label: "Schedule", icon: "calendar" },
    { href: "/en/venue", label: "Venue", icon: "mapPin" },
    { href: "/en/gallery", label: "Gallery", icon: "images" },
    { href: "/en/faq", label: "FAQ", icon: "circleHelp" },
  ],
  languageSwitchLabel: "TH",
  mobileMenuOpenLabel: "Open menu",
  mobileMenuCloseLabel: "Close menu",
  homeShell: {
    invitationCardEyebrow: "Save the date",
    invitationLeadIn: "Together with their families",
    formalNames: "Narueporn & Theerut",
    invitationInviteLine: "We invite you to celebrate our wedding",
    dateLabel: "Sunday, 29 November 2026",
    locationLabel: "Conrad Bangkok",
    invitationProgrammeSummary: "Morning ceremony and wedding reception",
    invitationCtaLabel: "View Details",
    invitationCtaHref: "/en#quick-actions",
    supportLineLabel: "Go to LINE Official Account",
    quickActionCards: [
      {
        href: "/en/schedule",
        title: "Schedule",
        subtitle: "View the wedding day timeline",
        icon: "calendar",
      },
      {
        href: "/en/venue",
        title: "Venue",
        subtitle: "Map and arrival information",
        icon: "mapPin",
      },
      {
        href: "/en/gallery",
        title: "Gallery",
        subtitle: "Our memories and photo updates",
        icon: "images",
      },
      {
        href: "/en/faq",
        title: "FAQ",
        subtitle: "Helpful information for guests",
        icon: "circleHelp",
      },
    ],
    welcomeTitle: "From us",
    welcomeMessage:
      "Thank you for being part of our special day. We hope this website helps you find everything you need before the celebration.",
  },
  footer: {
    thankYou: "Thank you for being part of our special day.",
    lineLabel: "Official updates channel",
    lineLinkText: "LINE OA",
    venueLabel: "Conrad Bangkok",
    footerLinks: [
      { href: "/en/schedule", label: "Schedule" },
      { href: "/en/venue", label: "Venue" },
      { href: "/en/gallery", label: "Gallery" },
      { href: "/en/faq", label: "FAQ" },
    ],
  },
};
