import type { SiteContent } from "@/content/schema";

export const siteContentEn: SiteContent = {
  locale: "en",
  htmlLang: "en",
  siteName: "Tan & Top Wedding",
  coupleFriendlyName: "Narueporn and Theerut",
  coupleFormalName: "Narueporn & Theerut",
  weddingDate: "Sunday, 29 November 2026",
  weddingDateISO: "2026-11-29T09:00:00+07:00",
  logoHref: "/",
  linePageHref: "/line",
  navDesktop: [
    { href: "/schedule", label: "Schedule" },
    { href: "/venue", label: "Venue" },
    { href: "/gallery", label: "Gallery" },
    { href: "/faq", label: "FAQ" },
  ],
  navMobile: [
    { href: "/schedule", label: "Schedule" },
    { href: "/venue", label: "Venue" },
    { href: "/gallery", label: "Gallery" },
    { href: "/faq", label: "FAQ" },
  ],
  bottomNav: [
    { href: "/", label: "Home", icon: "home" },
    { href: "/schedule", label: "Schedule", icon: "calendar" },
    { href: "/venue", label: "Venue", icon: "mapPin" },
    { href: "/gallery", label: "Gallery", icon: "images" },
    { href: "/faq", label: "FAQ", icon: "circleHelp" },
  ],
  languageSwitchLabel: "TH",
  mobileMenuOpenLabel: "Open menu",
  mobileMenuCloseLabel: "Close menu",
  homeShell: {
    invitationCardEyebrow: "Save the date",
    invitationLeadIn: "Together with our families",
    formalNames: "Narueporn & Theerut",
    invitationInviteLine: "We invite you to celebrate our wedding",
    invitationDateDisplay: {
      weekday: "Sunday",
      dayMonth: "29 November",
      year: "2026",
    },
    locationLabel: "Conrad Bangkok",
    venueHeading: "Venue",
    locationDetail: "All Seasons Place, Wireless Road, Bangkok",
    invitationVenueHref: "/venue",
    invitationProgrammeSummary: "Morning ceremonies and luncheon reception",
    invitationCtaLabel: "View Details",
    invitationCtaHref: "/#invitation",
    invitationOpenLabel: "Please tap to open",
    invitationSkipLabel: "Skip",
    countdownTitle: "Counting down to our wedding day",
    countdownLabels: {
      days: "Days",
      hours: "Hours",
      minutes: "Minutes",
      seconds: "Seconds",
    },
    invitationMailLabel: "You've got mail!",
    saveTheDateLabel: "Save the date",
    saveTheDateNumeric: "29.11.2026",
    timelineLead: "We hope you can join us",
    timelineTitle: "Our Timeline",
    timelineCtaLabel: "View full schedule",
    timelineCtaHref: "/schedule",
    supportLineLabel: "Go to LINE Official Account",
    quickActionCards: [
      {
        href: "/schedule",
        title: "Schedule",
        subtitle: "View the wedding day timeline",
        icon: "calendar",
      },
      {
        href: "/venue",
        title: "Venue",
        subtitle: "Map and arrival information",
        icon: "mapPin",
      },
      {
        href: "/gallery",
        title: "Gallery",
        subtitle: "Our memories and photo updates",
        icon: "images",
      },
      {
        href: "/faq",
        title: "FAQ",
        subtitle: "Helpful information for guests",
        icon: "circleHelp",
      },
    ],
    welcomeTitle: "From us",
    welcomeMessage:
      "We're so glad you're here. We hope this website helps you find everything you need before the celebration.",
    rsvpEyebrow: "RSVP",
    rsvpTitle: "Will you join us?",
    rsvpMessage: "Kindly let us know whether you can celebrate with us, so we can save a seat for you.",
    rsvpCtaLabel: "Reply to the invitation",
    rsvpFormUrl: "https://docs.google.com/forms/d/e/1FAIpQLSf7RrED_d3_tPbuLpYT7Ix2bok5HZX5Sg8ygNMXtiYtbkyjVg/viewform",
    rsvpPendingLabel: "RSVP link coming soon",
    rsvpNote: "Opens a short Google Form — it takes about a minute.",
  },
  footer: {
    thankYou: "Thank you for being part of our special day.",
    lineLabel: "Official updates channel",
    lineLinkText: "LINE OA",
    venueLabel: "Conrad Bangkok",
    footerLinks: [
      { href: "/schedule", label: "Schedule" },
      { href: "/venue", label: "Venue" },
      { href: "/gallery", label: "Gallery" },
      { href: "/faq", label: "FAQ" },
    ],
  },
};
