import type { SiteContent } from "@/content/schema";

export const siteContentEn: SiteContent = {
  locale: "en",
  htmlLang: "en",
  siteName: "Tan & Top Wedding",
  coupleFriendlyName: "Tan & Top",
  coupleFormalName: "Narueporn & Theerut",
  weddingDate: "Sunday, 29 November 2026",
  logoHref: "/en",
  linePageHref: "/en/line",
  navDesktop: [
    { href: "/en/schedule", label: "Schedule" },
    { href: "/en/venue", label: "Venue" },
    { href: "/en/gallery", label: "Gallery" },
    { href: "/en/faq", label: "FAQ" },
  ],
  navMobile: [
    { href: "/en/schedule", label: "Schedule" },
    { href: "/en/venue", label: "Venue" },
    { href: "/en/gallery", label: "Gallery" },
    { href: "/en/faq", label: "FAQ" },
  ],
  languageSwitchLabel: "TH",
  mobileMenuOpenLabel: "Open menu",
  mobileMenuCloseLabel: "Close menu",
  homeShell: {
    title: "Wedding 2026",
    formalNames: "Narueporn & Theerut",
    dateLabel: "Sunday, 29 November 2026",
    locationLabel: "Conrad Bangkok",
    intro:
      "We created this website as a simple and elegant wedding information hub for our guests, including the schedule, venue details, map, and gallery.",
    primaryCtaLabel: "View Schedule",
    primaryCtaHref: "/en/schedule",
    secondaryCtaLabel: "View Map",
    secondaryCtaHref: "/en/venue",
    supportLineLabel: "Go to LINE Official Account",
    quickLinks: [],
    quickLinksLabel: "Wedding Day at a Glance",
    glanceTitle: "Wedding Day at a Glance",
    glanceCards: [
      { label: "Date", value: "Sunday, 29 November 2026" },
      { label: "Venue", value: "Conrad Bangkok" },
      { label: "Programme", value: "Morning ceremony and wedding reception" },
    ],
    welcomeTitle: "From us",
    welcomeMessage:
      "Thank you for being part of our special day. We hope this website helps you find everything you need before the celebration.",
    heroImageAlt: "[Hero image placeholder]",
    heroImageCaption: "[Hero image placeholder]",
    heroImageCategory: "hero",
  },
  footer: {
    thankYou: "Thank you for being part of our special day.",
    lineLabel: "Official updates channel",
    lineLinkText: "LINE OA",
    venueLabel: "Conrad Bangkok",
    footerLinks: [
      { href: "/en/schedule", label: "Schedule" },
      { href: "/en/venue", label: "Venue" },
      { href: "/en/gallery", label: "Gallery" },
      { href: "/en/faq", label: "FAQ" },
    ],
  },
};
